src/Entity/Causes.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CausesRepository")
 */
class Causes
{
    use ContainedTrait;
    use EntityUuidTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;
    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    protected $startDate;
    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    protected $endDate;
    /**
     * @ORM\Column(type="float")
     * @Assert\PositiveOrZero()
     */
    private $totalNeeded;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Donation", mappedBy="cause")
     */
    private $donations;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="causes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $userCreator;

    public function __construct()
    {
        $this->donations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getStartDate(): ?DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(?DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(?DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getTotalNeeded(): ?float
    {
        return $this->totalNeeded;
    }

    public function setTotalNeeded(float $totalNeeded): self
    {
        $this->totalNeeded = $totalNeeded;

        return $this;
    }

    /**
     * @return Collection|Donation[]
     */
    public function getDonations(): Collection
    {
        return $this->donations;
    }

    public function addDonation(Donation $donation): self
    {
        if (!$this->donations->contains($donation)) {
            $this->donations[] = $donation;
            $donation->setCause($this);
        }

        return $this;
    }

    public function removeDonation(Donation $donation): self
    {
        if ($this->donations->contains($donation)) {
            $this->donations->removeElement($donation);
            // set the owning side to null (unless already changed)
            if ($donation->getCause() === $this) {
                $donation->setCause(null);
            }
        }

        return $this;
    }

    public function getUserCreator(): ?User
    {
        return $this->userCreator;
    }

    public function setUserCreator(?User $userCreator): self
    {
        $this->userCreator = $userCreator;

        return $this;
    }

}

src/Entity/TraitContent.php
<?php


namespace App\Entity;


trait TraitContent
{

    public function getExtrait()
    {
        return \mb_substr($this->content, 0, 50);
    }
}

src/Controller/CauseController.php
<?php

namespace App\Controller;

use App\Entity\Causes;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class CauseController
 * @package App\Controller
 */
class CauseController extends AbstractController
{
    /**
     * @Route("/cause", name="cause.public")
     * @param           PaginatorInterface $paginator
     * @param           Request            $request
     * @return          \Symfony\Component\HttpFoundation\Response
     */
    public function index(PaginatorInterface $paginator, Request $request)
    {
        $causesRepository = $this->getDoctrine()->getRepository(Causes::class);
        $causes = $paginator->paginate(
            $causesRepository->getPublished(),
            $request->query->getInt('page', 1),
            12
        );
        return $this->render('cause/index.html.twig', compact('causes'));
    }

    /**
     * @Route("/cause/{slug}", name="cause_details.public")
     * @param Causes $cause
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function show(Causes $cause)
    {
        return $this->render('cause/details.html.twig', compact('cause'));
    }
}

templates/cause/_causeCard.html.twig
<div class="causes_item">
    <div class="causes_img">
        {% if cause.imgFile %}
            <img class="img-fluid" src="{{ vich_uploader_asset(property,'imgFile')| imagine_filter('thumb') }}"
                 alt="{{ event.slug }}">
        {% else %}
            <img class="img-fluid" src="{{ asset('media/cause/empty.png') }}" alt="">
        {% endif %}
        <div class="c_parcent">
            <span></span>
        </div>
    </div>
    <div class="causes_text">
        <h4><a href="{{ path('cause_details.public',{'slug':cause.slug}) }}">{{ cause.title }}</a></h4>
        <p>{{ cause.extrait }}</p>
    </div>
    <div class="causes_bottom">
        <a href="#">Raised: $50,689</a>
        <a href="#">Total Need: ${{ cause.totalNeeded }}</a>
    </div>
</div>

templates/cause/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} Cause details{% endblock %}

{% block body %}
    <!--================Home Banner Area =================-->
    <section class="banner_area">
        <div class="banner_inner d-flex align-items-center">
            <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
            <div class="container">
                <div class="banner_content text-center">
                    <h2>Event Details</h2>
                    <div class="page_link">
                        <a href="#">Home</a>
                        <a href="event.html">Events</a>
                        <a href="event-details.html">Events Details</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Home Banner Area =================-->

    <!--================Event Details Area =================-->
    <section class="event_details_area p_120">
        <div class="container">
            <div class="event_d_inner">
                <img class="img-fluid" src="img/event/event-details.jpg" alt="">
                <div class="row event_text_inner">
                    <div class="col-lg-4">
                        <div class="left_text">
                            <ul class="list">
                                <li><a href="#"><i class="lnr lnr-calendar-full"></i>Saturday, 5th may, </a></li>
                                <li><a href="#"><i class="lnr lnr-apartment"></i>Rocky beach church</a></li>
                                <li><a href="#"><i class="lnr lnr-location"></i> Los Angeles, USA</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="right_text">
                            <h4>Spreading Peace to world</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident. sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Event Details Area =================-->
{% endblock %}

templates/cause/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }}
    Causes{% endblock %}

{% block body %}
    <!--================Home Banner Area =================-->
    <section class="banner_area">
        <div class="banner_inner d-flex align-items-center">
            <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
            <div class="container">
                <div class="banner_content text-center">
                    <h2>Causes</h2>
                    <div class="page_link">
                        <a href="{{ path('home.public') }}">Home</a>
                        <a href="{{ path('cause.public') }}">Causes</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Home Banner Area =================-->

    <!--================Causes Main Area =================-->
    <section class="event_main_area p_120">
        <div class="container">
            <div class="row event_main_inner">
                {% for cause in causes %}
                    <div class="col-sm-12 col-md-12 col-lg-6">
                        {{ include('cause/_causeCard.html.twig') }}
                    </div>
                {% endfor %}
            </div>
            <nav class="blog-pagination justify-content-center d-flex">
                <nav class="blog-pagination justify-content-center d-flex">
                    <ul class="pagination">
                        {{ knp_pagination_render(causes) }}
                    </ul>
                </nav>
            </nav>
        </div>
    </section>
    <!--================End Causes Main Area =================-->
{% endblock %}